# -*- coding: utf-8 -*-
"""11-20 darslar uchun qo'llanma matni."""

LESSONS = {}

LESSONS[11] = ("Lug'at (dictionary) bilan ishlash",
 "key-value juftliklar, qiymatga murojaat va o'zgartirish",
 [
  ("h2","1. Lug'at nima?"),
  ("p","**Lug'at (dictionary)** — bu **kalit (key)** va **qiymat (value)** juftliklaridan iborat tuzilma. U `{ }` ichida yoziladi. List indeks bilan ishlasa, lug'at kalit bilan ishlaydi."),
  ("code","f = {\n    'brand': 'Ford',\n    'model': 'Mustang',\n    'year': 1964,\n    'rang': 'Qora'\n}\nprint(f)",
   "Har bir juftlik: 'kalit': qiymat"),
  ("h2","2. Qiymatga murojaat"),
  ("p","Qiymatni olish uchun kalitni kvadrat qavsda yozamiz:"),
  ("code","f = {'brand': 'Ford', 'model': 'Mustang', 'year': 1964}\nprint(f['brand'])   # Ford\nprint(f['year'])    # 1964",
   "Kalit orqali qiymat olinadi."),
  ("h2","3. Qiymatni o'zgartirish va qo'shish"),
  ("code","f = {'brand': 'Ford', 'year': 1964}\nf['year'] = 2024       # o'zgartirish\nf['rang'] = 'Qizil'    # yangi juftlik qo'shish\nprint(f)",
   "Mavjud kalitga yozsak o'zgaradi, yangisiga qo'shiladi."),
  ("h2","4. get() — xavfsiz murojaat"),
  ("p","Agar kalit yo'q bo'lsa, `f['xato']` xato beradi. `get()` esa xato o'rniga `None` yoki belgilangan qiymat qaytaradi:"),
  ("code","f = {'brand': 'Ford'}\nprint(f.get('model'))            # None\nprint(f.get('model', 'mavjud emas'))","get() xavfsizroq."),
  ("h2","5. Lug'at metodlari"),
  ("bul",[
    "`keys()` — barcha kalitlar",
    "`values()` — barcha qiymatlar",
    "`items()` — kalit-qiymat juftliklari",
    "`del f['kalit']` — o'chirish",
  ]),
  ("code","f = {'brand': 'Ford', 'year': 1964}\nfor kalit, qiymat in f.items():\n    print(f\"{kalit}: {qiymat}\")",
   "Lug'atni tsikl bilan aylanish."),
  ("h2","Xulosa"),
  ("bul",[
    "Lug'at `{ }` ichida kalit:qiymat juftliklaridan iborat.",
    "Qiymat kalit orqali olinadi.",
    "`get()` xavfsiz murojaat qiladi.",
    "`items()` bilan tsiklda aylanamiz.",
  ]),
 ])

LESSONS[12] = ("Lug'atlar ro'yxati va murakkab tuzilmalar",
 "List ichida lug'atlar, lug'at ichida list",
 [
  ("h2","1. Lug'atlar ro'yxati"),
  ("p","Bir nechta o'xshash obyektni saqlash uchun lug'atlarni listga joylaymiz. Masalan, avtomobillar bazasi:"),
  ("code","car0 = {'model': 'lacetti', 'rang': 'oq', 'narx': 13000}\ncar1 = {'model': 'nexia', 'rang': 'qora', 'narx': 9000}\ncar2 = {'model': 'gentra', 'rang': 'qizil', 'narx': 15000}\nmashinalar = [car0, car1, car2]",
   "Uchta lug'at bitta ro'yxatda."),
  ("h2","2. Ro'yxatni tsikl bilan aylanish"),
  ("code","for mashina in mashinalar:\n    print(f\"{mashina['model']} - {mashina['narx']}$\")",
   "Har bir mashina ma'lumoti chiqadi."),
  ("h2","3. Shart bilan filtrlash"),
  ("p","Narxi ma'lum chegaradan past mashinalarni topish:"),
  ("code","for mashina in mashinalar:\n    if mashina['narx'] < 14000:\n        print(f\"Arzon: {mashina['model']}\")",
   "Shart asosida tanlab chiqaradi."),
  ("h2","4. Lug'at ichida list"),
  ("p","Lug'at qiymati sifatida list ham bo'lishi mumkin:"),
  ("code","talaba = {\n    'ism': 'Ali',\n    'fanlar': ['matematika', 'fizika', 'python']\n}\nfor fan in talaba['fanlar']:\n    print(fan)",
   "fanlar kaliti list saqlaydi."),
  ("h2","5. Statistik hisob"),
  ("code","jami = 0\nfor mashina in mashinalar:\n    jami += mashina['narx']\nprint(f\"Jami narx: {jami}$\")\nprint(f\"O'rtacha: {jami / len(mashinalar):.0f}$\")",
   "Yig'indi va o'rtacha qiymat."),
  ("h2","Xulosa"),
  ("bul",[
    "Lug'atlarni listga joylab baza tuzamiz.",
    "Tsikl + shart bilan ma'lumotni filtrlaymiz.",
    "Lug'at qiymati list yoki boshqa lug'at bo'lishi mumkin.",
  ]),
 ])

LESSONS[13] = ("List va lug'at masalalari",
 "Matnni tahlil qilish, so'zlarni sanash va eng ko'pini topish",
 [
  ("h2","1. Matnni so'zlarga ajratish"),
  ("p","`split()` metodi matnni bo'shliqlar bo'yicha so'zlar ro'yxatiga ajratadi:"),
  ("code","matn = 'Python juda qiziq Python tili'\nsozlar = matn.split()\nprint(sozlar)","['Python', 'juda', 'qiziq', 'Python', 'tili']"),
  ("h2","2. So'zlarni sanash (lug'at bilan)"),
  ("p","Har bir so'z necha marta uchraganini lug'atda saqlaymiz. `get(word, 0)` — agar so'z hali yo'q bo'lsa 0 dan boshlaydi:"),
  ("code","matn = input('Matn kiriting: ')\nsozlar = matn.split()\nsanagich = {}\nfor soz in sozlar:\n    sanagich[soz] = sanagich.get(soz, 0) + 1\nprint(sanagich)",
   "Har bir so'z nechta marta uchragani."),
  ("h2","3. Eng ko'p uchragan so'z"),
  ("p","`max()` funksiyasi `key` argumenti bilan eng katta qiymatli kalitni topadi:"),
  ("code","eng_kop = max(sanagich, key=sanagich.get)\nprint(f\"Eng ko'p so'z: {eng_kop}\")",
   "Eng ko'p takrorlangan so'zni topadi."),
  ("h2","4. Ro'yxatdagi takrorlarni olib tashlash"),
  ("p","`set()` takrorlanuvchi elementlarni avtomatik olib tashlaydi:"),
  ("code","sonlar = [1, 2, 2, 3, 3, 3, 4]\nnoyob = list(set(sonlar))\nprint(noyob)","[1, 2, 3, 4]"),
  ("h2","5. List comprehension (qisqa yozuv)"),
  ("p","Ro'yxatni bir qatorda yaratish mumkin:"),
  ("code","kvadratlar = [x**2 for x in range(1, 6)]\nprint(kvadratlar)","[1, 4, 9, 16, 25]"),
  ("h2","Xulosa"),
  ("bul",[
    "`split()` matnni so'zlarga ajratadi.",
    "Lug'at + `get()` bilan elementlarni sanaymiz.",
    "`max(d, key=d.get)` eng katta qiymatli kalitni beradi.",
    "`set()` takrorlarni olib tashlaydi.",
  ]),
 ])

LESSONS[14] = ("While tsikli",
 "Shartli takrorlash, break, continue va cheksiz tsikllar",
 [
  ("h2","1. While nima?"),
  ("p","**while** tsikli sharti `True` bo'lguncha kodni takrorlaydi. `for` aniq son marta ishlasa, `while` shart bajarilguncha ishlaydi:"),
  ("code","i = 1\nwhile i <= 6:\n    print(i)\n    i = i + 1","1 dan 6 gacha chiqadi."),
  ("note","Tsikl ichida shartni o'zgartirishni unutmang (i = i + 1). Aks holda tsikl cheksiz aylanadi!"),
  ("h2","2. break — tsiklni to'xtatish"),
  ("p","`break` tsiklni darhol to'xtatadi:"),
  ("code","while True:\n    son = input('Son kiriting (chiqish: x): ')\n    if son == 'x':\n        break\n    print(f\"Siz {son} kiritdingiz\")",
   "x kiritilsa tsikl tugaydi."),
  ("h2","3. continue — keyingi aylanaga o'tish"),
  ("p","`continue` joriy aylanani tashlab, keyingisiga o'tadi:"),
  ("code","i = 0\nwhile i < 6:\n    i += 1\n    if i == 3:\n        continue   # 3 ni tashlab ketadi\n    print(i)","3 dan tashqari hammasi chiqadi."),
  ("h2","4. Amaliy misol: yig'indi"),
  ("code","jami = 0\nson = int(input('Son (0 - to\\'xtatish): '))\nwhile son != 0:\n    jami += son\n    son = int(input('Son: '))\nprint(f\"Yig'indi: {jami}\")",
   "0 kiritilguncha sonlarni qo'shadi."),
  ("h2","5. while ... else"),
  ("code","i = 1\nwhile i <= 3:\n    print(i)\n    i += 1\nelse:\n    print('Tsikl tugadi')","else tsikl normal tugaganda ishlaydi."),
  ("h2","Xulosa"),
  ("bul",[
    "`while` shart rost bo'lguncha takrorlaydi.",
    "Shartni o'zgartiring, aks holda cheksiz tsikl.",
    "`break` to'xtatadi, `continue` keyingiga o'tadi.",
  ]),
 ])

LESSONS[15] = ("While tsikli — ro'yxat va lug'at bilan",
 "Foydalanuvchi kiritmalarini yig'ish va boshqarish",
 [
  ("h2","1. Ro'yxatni while bilan to'ldirish"),
  ("p","Foydalanuvchidan noma'lum sondagi ma'lumot olishda `while True` + `break` juda qulay:"),
  ("code","ismlar = []\nwhile True:\n    ism = input(\"Do'st ismi (yo'q - to'xtatish): \")\n    if ism == \"yo'q\":\n        break\n    ismlar.append(ism)\nprint(ismlar)",
   "Ismlar ro'yxatga yig'iladi."),
  ("h2","2. Tasdiqlash bilan davom etish"),
  ("code","ismlar = []\nwhile True:\n    ism = input('Ism kiriting: ')\n    ismlar.append(ism)\n    javob = input('Yana? (ha/yo\\'q) ').lower().strip()\n    if javob == \"yo'q\":\n        break\nprint(ismlar)",
   "Har safar davom etishni so'raydi."),
  ("h2","3. Ro'yxatdan elementlarni ko'chirish"),
  ("p","Bir ro'yxatdan ikkinchisiga element o'tkazish:"),
  ("code","tekshirilmagan = ['ali', 'vali', 'hasan']\ntekshirilgan = []\nwhile tekshirilmagan:\n    foydalanuvchi = tekshirilmagan.pop()\n    tekshirilgan.append(foydalanuvchi)\nprint(tekshirilgan)",
   "pop() oxirgini olib, ikkinchisiga qo'shadi."),
  ("h2","4. Lug'atni while bilan to'ldirish"),
  ("code","sorovnoma = {}\nwhile True:\n    ism = input('Ism: ')\n    javob = input('Sevimli rang: ')\n    sorovnoma[ism] = javob\n    yana = input('Yana? (ha/yo\\'q) ')\n    if yana == \"yo'q\":\n        break\nfor ism, rang in sorovnoma.items():\n    print(f\"{ism}: {rang}\")",
   "So'rovnoma natijalari lug'atda."),
  ("h2","5. Ma'lum qiymatni o'chirish"),
  ("code","hayvonlar = ['mushuk', 'it', 'mushuk', 'baliq', 'mushuk']\nwhile 'mushuk' in hayvonlar:\n    hayvonlar.remove('mushuk')\nprint(hayvonlar)","Barcha 'mushuk' o'chiriladi."),
  ("h2","Xulosa"),
  ("bul",[
    "`while True` + `break` noma'lum sondagi kiritma uchun ideal.",
    "`pop()` bilan ro'yxatlar orasida element ko'chiramiz.",
    "`while element in list` barcha takrorlarni o'chiradi.",
  ]),
 ])

LESSONS[16] = ("Funksiyalar — def",
 "Funksiya yaratish, chaqirish va parametrlar",
 [
  ("h2","1. Funksiya nima?"),
  ("p","**Funksiya** — bu ma'lum vazifani bajaruvchi, nom berilgan kod bloki. Bir marta yozib, ko'p marta ishlatish mumkin. `def` so'zi bilan yaratiladi:"),
  ("code","def salom_ber():\n    \"\"\"Salom beruvchi funksiya\"\"\"\n    print('Assalomu alaykum!')\n\nsalom_ber()",
   "Funksiyani nomi bilan chaqiramiz: salom_ber()"),
  ("note","def qatoridan keyingi \"\"\"...\"\"\" — docstring, funksiya nima qilishini tushuntiradi."),
  ("h2","2. Parametrli funksiya"),
  ("p","Funksiyaga ma'lumot uzatish uchun **parametr** ishlatiladi:"),
  ("code","def salom_ber(ism):\n    print(f'Salom, {ism}!')\n\nsalom_ber('Ali')\nsalom_ber('Vali')",
   "Har chaqiruvda turli ism beriladi."),
  ("h2","3. Bir nechta parametr"),
  ("code","def malumot(ism, yosh):\n    print(f'{ism}, {yosh} yoshda')\n\nmalumot('Ali', 20)","Tartib bo'yicha: ism='Ali', yosh=20"),
  ("h2","4. Kalit so'zli argumentlar"),
  ("p","Argumentni nomi bilan berish mumkin — tartib muhim emas:"),
  ("code","def malumot(ism, yosh):\n    print(f'{ism}, {yosh} yoshda')\n\nmalumot(yosh=20, ism='Ali')","Nom bilan berildi."),
  ("h2","5. Standart (default) qiymat"),
  ("p","Parametrga oldindan qiymat berib qo'yish mumkin:"),
  ("code","def salom_ber(ism, til='uz'):\n    if til == 'uz':\n        print(f'Salom, {ism}')\n    else:\n        print(f'Hello, {ism}')\n\nsalom_ber('Ali')          # uz\nsalom_ber('Ali', 'en')    # en",
   "til berilmasa 'uz' ishlatiladi."),
  ("h2","Xulosa"),
  ("bul",[
    "Funksiya `def` bilan yaratiladi, nomi bilan chaqiriladi.",
    "Parametrlar orqali ma'lumot uzatiladi.",
    "Argumentni nom bilan ham berish mumkin.",
    "Standart qiymat — chaqirishda ixtiyoriy bo'ladi.",
  ]),
 ])

LESSONS[17] = ("Funksiyalar — return (qiymat qaytarish)",
 "Natija qaytarish, uni saqlash va ishlatish",
 [
  ("h2","1. return nima?"),
  ("p","`return` funksiya natijasini **qaytaradi**. `print()` faqat ekranga chiqaradi, `return` esa qiymatni keyin ishlatish uchun beradi:"),
  ("code","def toliq_ism(ism, familiya):\n    \"\"\"To'liq ismni qaytaradi\"\"\"\n    return f'{ism} {familiya}'\n\ntalaba = toliq_ism('olim', 'hakimov')\nprint(talaba)",
   "Natija o'zgaruvchiga saqlandi."),
  ("h2","2. return va print farqi"),
  ("bul",[
    "`print()` — ekranga ko'rsatadi, natijani saqlab bo'lmaydi.",
    "`return` — qiymatni qaytaradi, uni o'zgaruvchiga olish mumkin.",
    "`return` dan keyingi kod ishlamaydi (funksiya tugaydi).",
  ]),
  ("h2","3. Hisob-kitob qaytarish"),
  ("code","def yigindi(a, b):\n    return a + b\n\nnatija = yigindi(5, 3)\nprint(natija * 2)   # 16",
   "Qaytgan natijani amalda ishlatdik."),
  ("h2","4. Bir nechta qiymat qaytarish"),
  ("p","Funksiya bir vaqtda bir nechta qiymat qaytarishi mumkin:"),
  ("code","def min_max(sonlar):\n    return min(sonlar), max(sonlar)\n\nkichik, katta = min_max([3, 7, 1, 9])\nprint(kichik, katta)   # 1 9",
   "Ikkala qiymatni alohida oldik."),
  ("h2","5. Shartli return"),
  ("code","def juftmi(son):\n    if son % 2 == 0:\n        return 'juft'\n    return 'toq'\n\nprint(juftmi(10))   # juft\nprint(juftmi(7))    # toq",
   "Shartga qarab har xil natija."),
  ("h2","Xulosa"),
  ("bul",[
    "`return` natijani qaytaradi, `print` faqat ko'rsatadi.",
    "Qaytgan qiymatni o'zgaruvchiga saqlab ishlatamiz.",
    "Bir nechta qiymat vergul bilan qaytariladi.",
  ]),
 ])

LESSONS[18] = ("*args, **kwargs va modullar",
 "Cheksiz argumentlar va funksiyalarni alohida faylga ajratish",
 [
  ("h2","1. *args — cheksiz argumentlar"),
  ("p","Agar funksiyaga nechta argument kelishini bilmasak, parametr oldiga `*` qo'yamiz. Ular **kortej (tuple)** ko'rinishida yig'iladi:"),
  ("code","def summa(*sonlar):\n    yigindi = 0\n    for son in sonlar:\n        yigindi += son\n    return yigindi\n\nprint(summa(1, 2))            # 3\nprint(summa(1, 2, 3, 4, 5))  # 15",
   "Istalgancha son berish mumkin."),
  ("h2","2. **kwargs — nomli cheksiz argumentlar"),
  ("p","`**` bilan nomli argumentlar **lug'at** ko'rinishida yig'iladi:"),
  ("code","def profil(**malumot):\n    for kalit, qiymat in malumot.items():\n        print(f'{kalit}: {qiymat}')\n\nprofil(ism='Ali', yosh=20, shahar='Toshkent')",
   "Nomli argumentlar lug'atga tushadi."),
  ("h2","3. Modul nima?"),
  ("p","**Modul** — bu funksiyalar saqlanadigan alohida `.py` fayl. Uni boshqa faylga `import` qilib ishlatamiz. Bu kodni tartibli saqlashga yordam beradi."),
  ("code","# avto_info.py faylida:\ndef avto_korsat(ishlab, model):\n    return f'{ishlab} {model}'","Funksiya alohida faylda."),
  ("h2","4. Modulni import qilish"),
  ("code","import avto_info\nprint(avto_info.avto_korsat('Toyota', 'Camry'))\n\n# yoki faqat bitta funksiyani:\nfrom avto_info import avto_korsat\nprint(avto_korsat('Kia', 'K5'))",
   "import — modulni ulaydi."),
  ("h2","5. Taxallus (as)"),
  ("code","import avto_info as ai\nprint(ai.avto_korsat('BMW', 'X5'))","as — qisqa nom beradi."),
  ("h2","Xulosa"),
  ("bul",[
    "`*args` — cheksiz oddiy argumentlar (tuple).",
    "`**kwargs` — cheksiz nomli argumentlar (dict).",
    "Modul — funksiyalarni alohida faylda saqlash.",
    "`import` va `from ... import` bilan ulaymiz.",
  ]),
 ])

LESSONS[19] = ("Klasslar — OOP bilan tanishuv",
 "class, obyekt, __init__ va metodlar",
 [
  ("h2","1. OOP va class nima?"),
  ("p","**OOP (Obyektga yo'naltirilgan dasturlash)** — real dunyo narsalarini kod orqali ifodalash usuli. **Class (sinf)** — bu obyekt yaratish uchun \"chizma\", obyekt esa shu chizma asosida yaratilgan nusxa."),
  ("code","class MyClass:\n    x = 5\n\np1 = MyClass()   # obyekt yaratish\nprint(p1.x)      # 5",
   "MyClass — sinf, p1 — obyekt."),
  ("h2","2. __init__ — konstruktor"),
  ("p","`__init__` metodi obyekt yaratilganda avtomatik ishga tushadi va boshlang'ich qiymatlarni o'rnatadi. `self` — obyektning o'ziga ishora qiladi:"),
  ("code","class Person:\n    def __init__(self, ism, yosh):\n        self.ism = ism\n        self.yosh = yosh\n\np1 = Person('Ali', 20)\nprint(p1.ism)    # Ali\nprint(p1.yosh)   # 20",
   "self.ism — obyekt xususiyati (atribut)."),
  ("h2","3. Metodlar — obyekt funksiyalari"),
  ("p","Sinf ichidagi funksiyalar **metod** deyiladi. Ular obyekt bilan ish qiladi:"),
  ("code","class Person:\n    def __init__(self, ism, yosh):\n        self.ism = ism\n        self.yosh = yosh\n    def tanishtir(self):\n        print(f\"Men {self.ism}, {self.yosh} yoshdaman\")\n\np1 = Person('Ali', 20)\np1.tanishtir()",
   "Metod self orqali atributlardan foydalanadi."),
  ("h2","4. Atributni o'zgartirish"),
  ("code","p1 = Person('Ali', 20)\np1.yosh = 21\nprint(p1.yosh)   # 21","Obyekt atributini to'g'ridan-to'g'ri o'zgartirish."),
  ("h2","5. Bir nechta obyekt"),
  ("code","p1 = Person('Ali', 20)\np2 = Person('Vali', 25)\np1.tanishtir()\np2.tanishtir()","Bir sinfdan ko'p obyekt yaratiladi."),
  ("h2","Xulosa"),
  ("bul",[
    "Class — chizma, obyekt — undan yaratilgan nusxa.",
    "`__init__` boshlang'ich qiymatlarni o'rnatadi.",
    "`self` obyektning o'ziga ishora qiladi.",
    "Metod — sinf ichidagi funksiya.",
  ]),
 ])

LESSONS[20] = ("Meros (inheritance)",
 "Ota-ona va bola sinflar, super() va metodlarni qayta yozish",
 [
  ("h2","1. Meros nima?"),
  ("p","**Meros (inheritance)** — bir sinf (bola) boshqa sinf (ota-ona) xususiyat va metodlarini olishi. Bu kodni qayta ishlatishga yordam beradi."),
  ("code","class Person:\n    def __init__(self, ism, familiya):\n        self.ism = ism\n        self.familiya = familiya\n    def korsat(self):\n        print(self.ism, self.familiya)\n\nx = Person('Abror', 'Jamolov')\nx.korsat()",
   "Ota-ona sinf."),
  ("h2","2. Bola sinf yaratish"),
  ("p","Bola sinf qavs ichida ota-ona nomini yozadi va uning hamma narsasini meros qilib oladi:"),
  ("code","class Student(Person):\n    pass\n\ns = Student('Ali', 'Valiyev')\ns.korsat()   # ota-onadan meros olingan metod",
   "Student — Person'dan meros oldi."),
  ("h2","3. super() — ota-ona __init__ ni chaqirish"),
  ("p","Bola sinf o'z `__init__` ga ega bo'lsa, ota-onanikini `super()` orqali chaqiradi:"),
  ("code","class Student(Person):\n    def __init__(self, ism, familiya, kurs):\n        super().__init__(ism, familiya)\n        self.kurs = kurs\n\ns = Student('Ali', 'Valiyev', 2)\nprint(s.ism, s.kurs)",
   "super() ota-ona qiymatlarini o'rnatadi."),
  ("h2","4. Metodni qayta yozish (override)"),
  ("p","Bola sinf ota-ona metodini o'zgartirib yozishi mumkin:"),
  ("code","class Student(Person):\n    def korsat(self):\n        print(f'Talaba: {self.ism}')\n\ns = Student('Ali', 'Valiyev')\ns.korsat()   # bola sinf versiyasi ishlaydi",
   "Bir nomli metod ota-onanikini almashtiradi."),
  ("h2","5. Yangi metod qo'shish"),
  ("code","class Student(Person):\n    def oqimoq(self):\n        print(f'{self.ism} dars o\\'qiyapti')","Bola sinf yangi xatti-harakat qo'shishi mumkin."),
  ("h2","Xulosa"),
  ("bul",[
    "Meros — bola sinf ota-ona xususiyatlarini oladi.",
    "`super()` ota-ona __init__ ni chaqiradi.",
    "Metodni qayta yozib (override) o'zgartirish mumkin.",
    "Bola sinf yangi metodlar qo'shishi mumkin.",
  ]),
 ])
