# -*- coding: utf-8 -*-
"""21-29 darslar uchun qo'llanma matni."""

LESSONS = {}

LESSONS[21] = ("Iteratorlar",
 "iter(), next(), iterator protokoli va o'z iteratoringizni yaratish",
 [
  ("h2","1. Iterator nima?"),
  ("p","**Iterator** — bu elementlarni birma-bir qaytaruvchi obyekt. List, tuple, string — bularning hammasi iteratsiya qilinadigan (iterable) obyektlardir. `iter()` ulardan iterator yasaydi, `next()` esa keyingi elementni oladi:"),
  ("code","mevalar = ('olma', 'banan', 'gilos')\nit = iter(mevalar)\nprint(next(it))   # olma\nprint(next(it))   # banan\nprint(next(it))   # gilos",
   "next() har safar keyingi elementni beradi."),
  ("h2","2. String ham iterator"),
  ("code","matn = 'Python'\nit = iter(matn)\nprint(next(it))   # P\nprint(next(it))   # y",
   "Har bir harf alohida olinadi."),
  ("h2","3. for tsikli aslida iterator ishlatadi"),
  ("p","`for` tsikli ortda `iter()` va `next()` ni o'zi chaqiradi. Elementlar tugaganda `StopIteration` yuz beradi va tsikl to'xtaydi:"),
  ("code","for meva in ('olma', 'banan'):\n    print(meva)","for — iteratorning qulay shakli."),
  ("h2","4. O'z iteratoringizni yaratish"),
  ("p","Sinfga `__iter__` va `__next__` metodlarini qo'shib, o'z iteratoringizni yasaysiz:"),
  ("code","class Sanagich:\n    def __iter__(self):\n        self.a = 1\n        return self\n    def __next__(self):\n        if self.a <= 5:\n            x = self.a\n            self.a += 1\n            return x\n        else:\n            raise StopIteration\n\nfor son in Sanagich():\n    print(son)",
   "1 dan 5 gacha chiqaradi."),
  ("note","StopIteration tsiklni to'xtatadi. Aks holda iterator cheksiz davom etadi."),
  ("h2","Xulosa"),
  ("bul",[
    "`iter()` iterator yasaydi, `next()` keyingi elementni beradi.",
    "List, tuple, string — iterable obyektlar.",
    "`for` ichida iter/next avtomatik ishlaydi.",
    "`__iter__` va `__next__` bilan o'z iteratoringiz.",
  ]),
 ])

LESSONS[22] = ("Polimorfizm",
 "Bir funksiya — turli turlar, len(), metod polimorfizmi",
 [
  ("h2","1. Polimorfizm nima?"),
  ("p","**Polimorfizm** — \"ko'p shakllilik\" degani. Bir funksiya yoki metod turli turdagi obyektlar bilan ishlay olishi. Masalan, `len()` ham matn, ham list, ham lug'at uchun ishlaydi:"),
  ("code","print(len('Salom'))            # 5 (belgilar soni)\nprint(len(['a', 'b', 'c']))    # 3 (elementlar soni)\nprint(len({'a': 1, 'b': 2}))   # 2 (kalitlar soni)",
   "len() har xil turga moslashadi."),
  ("h2","2. + operatori polimorfizmi"),
  ("code","print(5 + 3)            # 8 (qo'shish)\nprint('Sa' + 'lom')    # Salom (birlashtirish)\nprint([1, 2] + [3, 4])  # [1,2,3,4]",
   "+ turga qarab boshqacha ishlaydi."),
  ("h2","3. Sinf metodlari polimorfizmi"),
  ("p","Turli sinflarda bir nomli metod bo'lsa, ularni bir xil chaqirish mumkin:"),
  ("code","class Mushuk:\n    def ovoz(self):\n        print('Miyov')\nclass It:\n    def ovoz(self):\n        print('Vov')\n\nfor hayvon in (Mushuk(), It()):\n    hayvon.ovoz()",
   "Har bir obyekt o'z ovoz() metodini ishlatadi."),
  ("h2","4. Meros bilan polimorfizm"),
  ("code","class Transport:\n    def harakat(self):\n        print('Harakatlanmoqda')\nclass Mashina(Transport):\n    def harakat(self):\n        print('Yo\\'lda ketmoqda')\nclass Qayiq(Transport):\n    def harakat(self):\n        print('Suzmoqda')\n\nfor t in (Mashina(), Qayiq()):\n    t.harakat()",
   "Bir metod nomi, turli xatti-harakat."),
  ("h2","Xulosa"),
  ("bul",[
    "Polimorfizm — bir nom, turli xatti-harakat.",
    "`len()`, `+` — o'rnatilgan polimorfik vositalar.",
    "Turli sinflarda bir nomli metodlar moslashadi.",
    "Meros bilan polimorfizm OOP'ning kuchli tomoni.",
  ]),
 ])

LESSONS[23] = ("O'zgaruvchi doirasi (scope)",
 "Lokal va global o'zgaruvchilar, global va nonlocal",
 [
  ("h2","1. Doira (scope) nima?"),
  ("p","**Doira** — o'zgaruvchi qayerda ko'rinadi va ishlatiladi degani. Funksiya ichida yaratilgan o'zgaruvchi **lokal** bo'ladi va faqat shu funksiya ichida ishlaydi:"),
  ("code","def myfunc():\n    x = 300   # lokal o'zgaruvchi\n    print(x)\n\nmyfunc()      # 300\n# print(x)    # XATO! x bu yerda yo'q",
   "x faqat funksiya ichida mavjud."),
  ("h2","2. Global o'zgaruvchi"),
  ("p","Funksiyadan tashqarida yaratilgan o'zgaruvchi **global** bo'ladi va hamma joyda ko'rinadi:"),
  ("code","x = 300   # global\n\ndef myfunc():\n    print(x)   # global x ni o'qiy oladi\n\nmyfunc()   # 300",
   "Global o'zgaruvchini funksiya o'qiy oladi."),
  ("h2","3. Bir xil nom — turli doira"),
  ("code","x = 300\ndef myfunc():\n    x = 200   # bu yangi lokal x\n    print(x)  # 200\nmyfunc()\nprint(x)      # 300 (global o'zgarmadi)",
   "Lokal x global x ga ta'sir qilmaydi."),
  ("h2","4. global kalit so'zi"),
  ("p","Funksiya ichidan global o'zgaruvchini o'zgartirish uchun `global` ishlatiladi:"),
  ("code","x = 300\ndef myfunc():\n    global x\n    x = 200   # endi global x o'zgaradi\nmyfunc()\nprint(x)      # 200",
   "global bilan tashqi o'zgaruvchi o'zgaradi."),
  ("h2","5. nonlocal — ichki funksiya"),
  ("code","def tashqi():\n    x = 'oddiy'\n    def ichki():\n        nonlocal x\n        x = 'o\\'zgargan'\n    ichki()\n    print(x)   # o'zgargan\ntashqi()",
   "nonlocal yaqin tashqi doiradagi o'zgaruvchini o'zgartiradi."),
  ("h2","Xulosa"),
  ("bul",[
    "Lokal o'zgaruvchi faqat funksiya ichida ishlaydi.",
    "Global o'zgaruvchi hamma joyda ko'rinadi.",
    "`global` tashqi o'zgaruvchini o'zgartiradi.",
    "`nonlocal` ichki funksiyada tashqi doirani o'zgartiradi.",
  ]),
 ])

LESSONS[24] = ("Sana-vaqt va JSON",
 "datetime moduli, sana formatlash va JSON bilan ishlash",
 [
  ("h2","1. datetime moduli"),
  ("p","`datetime` moduli sana va vaqt bilan ishlash uchun ishlatiladi. Uni `import` qilish kerak:"),
  ("code","import datetime\nhozir = datetime.datetime.now()\nprint(hozir)   # joriy sana va vaqt",
   "now() hozirgi vaqtni beradi."),
  ("h2","2. Sananing qismlarini olish"),
  ("code","import datetime\nx = datetime.datetime.now()\nprint(x.year)    # yil\nprint(x.month)   # oy\nprint(x.day)     # kun\nprint(x.hour)    # soat",
   "Yil, oy, kun, soatni alohida olish."),
  ("h2","3. Sanani formatlash — strftime()"),
  ("p","`strftime()` sanani chiroyli matnga aylantiradi:"),
  ("code","import datetime\nx = datetime.datetime.now()\nprint(x.strftime('%d.%m.%Y'))   # 16.06.2026\nprint(x.strftime('%H:%M'))      # 14:30",
   "%d kun, %m oy, %Y yil, %H soat, %M daqiqa."),
  ("h2","4. JSON nima?"),
  ("p","**JSON** — ma'lumot almashish formati. U Python lug'atiga juda o'xshaydi. `json` moduli Python obyektini JSON matniga va aksincha aylantiradi:"),
  ("code","import json\nodam = {'ism': 'Ali', 'yosh': 20}\nmatn = json.dumps(odam)   # lug'at -> JSON matn\nprint(matn)",
   "dumps() — Python obyektini JSON matniga."),
  ("h2","5. JSON matnini o'qish — loads()"),
  ("code","import json\nmatn = '{\"ism\": \"Ali\", \"yosh\": 20}'\nodam = json.loads(matn)   # JSON matn -> lug'at\nprint(odam['ism'])        # Ali",
   "loads() — JSON matnini Python lug'atiga."),
  ("h2","Xulosa"),
  ("bul",[
    "`datetime.now()` joriy sana-vaqtni beradi.",
    "`strftime()` sanani formatlaydi.",
    "JSON — ma'lumot almashish formati.",
    "`json.dumps()` va `json.loads()` o'zaro aylantiradi.",
  ]),
 ])

LESSONS[25] = ("Regulyar ifodalar (re moduli)",
 "Matnda namuna qidirish, search, findall va almashtirish",
 [
  ("h2","1. re moduli nima?"),
  ("p","**Regulyar ifoda (regex)** — matnda ma'lum namunani qidirish vositasi. `re` moduli telefon raqami, email, sana kabi naqshlarni topishda juda foydali:"),
  ("code","import re\nmatn = 'Men Python tilini o\\'rganaman'\nnatija = re.search('Python', matn)\nif natija:\n    print('Topildi!')\nelse:\n    print('Topilmadi')",
   "search() namunani qidiradi."),
  ("h2","2. Maxsus belgilar"),
  ("bul",[
    "`\\d` — raqam (0-9)",
    "`\\w` — harf, raqam yoki _",
    "`\\s` — bo'sh joy",
    "`+` — bir yoki ko'p marta, `*` — nol yoki ko'p marta",
    "`.` — istalgan belgi",
  ]),
  ("h2","3. findall() — barchasini topish"),
  ("code","import re\nmatn = 'Telefon: 90, 91, 99'\nraqamlar = re.findall(r'\\d+', matn)\nprint(raqamlar)   # ['90', '91', '99']",
   "findall barcha mosliklarni ro'yxat qiladi."),
  ("h2","4. sub() — almashtirish"),
  ("code","import re\nmatn = 'Salom    dunyo'\ntoza = re.sub(r'\\s+', ' ', matn)\nprint(toza)   # Salom dunyo",
   "Ortiqcha bo'shliqlarni bittaga almashtirdi."),
  ("h2","5. split() — namuna bo'yicha bo'lish"),
  ("code","import re\nmatn = 'olma,banan;gilos uzum'\nmevalar = re.split(r'[,; ]', matn)\nprint(mevalar)","Vergul, nuqta-vergul va bo'shliq bo'yicha bo'ldi."),
  ("note","r'...' (raw string) regex yozishda \\ ni to'g'ri ishlatish uchun tavsiya etiladi."),
  ("h2","Xulosa"),
  ("bul",[
    "`re.search()` — birinchi mos kelganini topadi.",
    "`re.findall()` — barchasini ro'yxat qiladi.",
    "`re.sub()` — almashtiradi, `re.split()` — bo'ladi.",
    "`\\d`, `\\w`, `\\s`, `+`, `*` — asosiy belgilar.",
  ]),
 ])

LESSONS[26] = ("Fayllar bilan ishlash",
 "Fayl ochish, o'qish, yozish va with bloki",
 [
  ("h2","1. Faylni ochish va o'qish"),
  ("p","`open()` funksiyasi faylni ochadi, `read()` esa uning butun mazmunini o'qiydi:"),
  ("code","f = open('myfile.txt')\nprint(f.read())\nf.close()   # faylni yopish shart",
   "open() ochadi, read() o'qiydi, close() yopadi."),
  ("h2","2. with bloki — xavfsiz usul"),
  ("p","`with` bloki faylni avtomatik yopadi — `close()` yozish shart emas. Bu eng tavsiya etiladigan usul:"),
  ("code","with open('myfile.txt') as f:\n    matn = f.read()\n    print(matn)",
   "Blokdan chiqishda fayl avtomatik yopiladi."),
  ("h2","3. Ochish rejimlari"),
  ("bul",[
    "`'r'` — o'qish (read), standart rejim",
    "`'w'` — yozish (write), eski mazmunni o'chiradi",
    "`'a'` — qo'shish (append), oxiriga yozadi",
    "`'x'` — yangi fayl yaratish",
  ]),
  ("h2","4. Faylga yozish"),
  ("code","with open('myfile.txt', 'w') as f:\n    f.write('Birinchi qator\\n')\n    f.write('Ikkinchi qator\\n')",
   "'w' — eski mazmun o'chadi va yangi yoziladi."),
  ("h2","5. Faylga qo'shish va qatorma-qator o'qish"),
  ("code","with open('myfile.txt', 'a') as f:\n    f.write('Yangi qator\\n')\n\nwith open('myfile.txt') as f:\n    for qator in f:\n        print(qator.strip())",
   "'a' qo'shadi, for bilan qatorlarni o'qiymiz."),
  ("note","Fayl topilmasa FileNotFoundError yuz beradi. Buni try/except bilan ushlash mumkin."),
  ("h2","Xulosa"),
  ("bul",[
    "`open()` faylni ochadi, `read()` o'qiydi.",
    "`with` bloki faylni avtomatik yopadi.",
    "Rejimlar: 'r' o'qish, 'w' yozish, 'a' qo'shish.",
    "`for qator in f` bilan qatorma-qator o'qiymiz.",
  ]),
 ])

LESSONS[27] = ("OS moduli va NumPy bilan tanishuv",
 "Operatsion tizim bilan ishlash va massivlar",
 [
  ("h2","1. os moduli nima?"),
  ("p","`os` moduli operatsion tizim bilan ishlash imkonini beradi: fayl va papkalarni yaratish, o'chirish, ko'chirish:"),
  ("code","import os\nos.remove('myfile.txt')   # faylni o'chiradi","remove() faylni o'chiradi."),
  ("h2","2. Fayl mavjudligini tekshirish"),
  ("p","Faylni o'chirishdan oldin uning borligini tekshirish xavfsizroq:"),
  ("code","import os\nfayl = 'myfile.txt'\nif os.path.exists(fayl):\n    os.remove(fayl)\n    print('O\\'chirildi')\nelse:\n    print('Fayl topilmadi')",
   "path.exists() borligini tekshiradi."),
  ("h2","3. Papka bilan ishlash"),
  ("code","import os\nos.mkdir('yangi_papka')      # papka yaratish\nprint(os.listdir('.'))       # joriy papkadagi fayllar\nprint(os.getcwd())           # joriy papka manzili",
   "mkdir yaratadi, listdir ro'yxatlaydi."),
  ("h2","4. NumPy nima?"),
  ("p","**NumPy** — sonli hisob-kitoblar uchun kuchli kutubxona. Uning asosi — **massiv (array)**, oddiy listdan tezroq va qulayroq. Avval `pip install numpy` qilinadi:"),
  ("code","import numpy as np\nmassiv = np.array([1, 2, 3, 4, 5])\nprint(massiv)\nprint(massiv * 2)   # [2 4 6 8 10]",
   "Massivga amal har bir elementga qo'llanadi."),
  ("h2","5. NumPy foydali funksiyalari"),
  ("code","import numpy as np\na = np.array([10, 20, 30, 40])\nprint(a.sum())    # 100\nprint(a.mean())   # 25.0 (o'rtacha)\nprint(a.max())    # 40",
   "sum, mean, max — statistik amallar."),
  ("h2","Xulosa"),
  ("bul",[
    "`os` moduli fayl va papkalar bilan ishlaydi.",
    "`os.path.exists()` borligini tekshiradi.",
    "NumPy — tez sonli hisob-kitoblar kutubxonasi.",
    "Massivga amallar har bir elementga qo'llanadi.",
  ]),
 ])

LESSONS[28] = ("Random va NumPy bilan ishlash",
 "Tasodifiy sonlar generatsiyasi va NumPy massivlari",
 [
  ("h2","1. random moduli"),
  ("p","Tasodifiy son kerak bo'lganda (o'yinlar, testlar) `random` ishlatiladi:"),
  ("code","import random\nprint(random.randint(1, 100))   # 1-100 oralig'ida tasodifiy butun son\nprint(random.random())          # 0-1 oralig'ida kasr",
   "randint butun, random kasr son beradi."),
  ("h2","2. Ro'yxatdan tasodifiy tanlash"),
  ("code","import random\nmevalar = ['olma', 'banan', 'gilos']\nprint(random.choice(mevalar))   # tasodifiy bitta\nrandom.shuffle(mevalar)         # aralashtiradi\nprint(mevalar)",
   "choice — tanlaydi, shuffle — aralashtiradi."),
  ("h2","3. NumPy random"),
  ("p","NumPy ham tasodifiy sonlar generatsiya qiladi, ayniqsa massivlar uchun:"),
  ("code","from numpy import random\nx = random.randint(100)         # bitta son\nprint(x)\ny = random.randint(100, size=5) # 5 ta sonli massiv\nprint(y)",
   "size — massiv o'lchamini belgilaydi."),
  ("h2","4. Tasodifiy kasr massiv"),
  ("code","from numpy import random\nx = random.rand(3)      # 3 ta kasr son\nprint(x)\nm = random.rand(2, 3)   # 2x3 massiv\nprint(m)",
   "rand() 0-1 oralig'ida kasr sonlar."),
  ("h2","5. Ehtimollik bilan tanlash"),
  ("code","from numpy import random\nx = random.choice([3, 5, 7, 9], size=5)\nprint(x)",
   "Berilgan qiymatlardan tasodifiy tanlaydi."),
  ("h2","Xulosa"),
  ("bul",[
    "`random.randint()` — tasodifiy butun son.",
    "`random.choice()` va `shuffle()` ro'yxat bilan.",
    "NumPy `random` massivlar uchun qulay.",
    "`size` argumenti massiv o'lchamini belgilaydi.",
  ]),
 ])

LESSONS[29] = ("Kutubxonalar va NumPy davomi",
 "frompyfunc, universal funksiyalar va kutubxonalardan foydalanish",
 [
  ("h2","1. Kutubxona (library) nima?"),
  ("p","**Kutubxona** — boshqalar yozgan, tayyor funksiyalar to'plami. Ularni o'rnatib (`pip install`), import qilib ishlatamiz. Bu vaqtni tejaydi va kuchli imkoniyatlar beradi."),
  ("bul",[
    "**NumPy** — sonli hisoblar va massivlar",
    "**Pandas** — jadval ma'lumotlari tahlili",
    "**Matplotlib** — grafiklar chizish",
    "**Requests** — internetdan ma'lumot olish",
  ]),
  ("h2","2. NumPy universal funksiyalari (ufunc)"),
  ("p","`frompyfunc()` oddiy Python funksiyasini massivlar bilan ishlaydigan universal funksiyaga aylantiradi:"),
  ("code","import numpy as np\ndef qoshish(x, y):\n    return x + y\n\nqoshish = np.frompyfunc(qoshish, 2, 1)\nprint(qoshish([1, 2, 3, 4], [5, 6, 7, 8]))",
   "Natija: [6 8 10 12] — juftma-juft qo'shildi."),
  ("h2","3. Tayyor ufunc'lar"),
  ("code","import numpy as np\na = np.array([1, 2, 3, 4])\nprint(np.add(a, 10))      # har biriga 10 qo'shadi\nprint(np.sqrt(a))         # kvadrat ildiz\nprint(np.power(a, 2))     # kvadrati",
   "add, sqrt, power — tayyor amallar."),
  ("h2","4. Massiv shaklini o'zgartirish"),
  ("code","import numpy as np\na = np.array([1, 2, 3, 4, 5, 6])\nb = a.reshape(2, 3)   # 2 qator, 3 ustun\nprint(b)",
   "reshape massiv o'lchamini o'zgartiradi."),
  ("h2","5. Kutubxonadan foydalanish bosqichlari"),
  ("bul",[
    "Terminalda o'rnating: `pip install numpy`",
    "Faylga import qiling: `import numpy as np`",
    "Hujjatlarni o'qib, funksiyalardan foydalaning.",
    "Kichik misollar bilan sinab ko'ring.",
  ]),
  ("h2","Xulosa va keyingi qadamlar"),
  ("bul",[
    "Kutubxonalar tayyor kuchli vositalar beradi.",
    "`frompyfunc` oddiy funksiyani ufunc qiladi.",
    "NumPy'da add, sqrt, reshape kabi ko'p amallar bor.",
    "Endi Pandas, Matplotlib va veb-freymvorklarni o'rganishingiz mumkin!",
  ]),
 ])
