# -*- coding: utf-8 -*-
"""1-10 darslar uchun qo'llanma matni."""

LESSONS = {}

LESSONS[1] = ("Python bilan tanishuv va print()",
 "Birinchi dastur, ekranga ma'lumot chiqarish va f-string asoslari",
 [
  ("h2","1. Python nima va u nimaga kerak?"),
  ("p","Python — bu o'rganish oson, kuchli va dunyoda eng ko'p ishlatiladigan dasturlash tillaridan biri. U sun'iy intellekt, veb-saytlar, o'yinlar, ma'lumotlar tahlili va kundalik ishlarni avtomatlashtirishda keng qo'llaniladi."),
  ("bul",[
    "Sintaksisi sodda — kod oddiy o'zbek/ingliz tilidagi gaplarga o'xshaydi.",
    "Bepul va ochiq manbali (open source).",
    "Juda katta tayyor kutubxonalar to'plamiga ega.",
    "Boshlovchilar uchun eng tavsiya etiladigan til.",
  ]),
  ("h2","2. Birinchi dasturimiz"),
  ("p","Dasturlashda an'anaga ko'ra birinchi dastur ekranga \"Salom dunyo\" yozadi. Buning uchun `print()` funksiyasidan foydalanamiz. `print` so'zi inglizchada \"chop et\" degani."),
  ("code",'print("Salom dunyo")','Natija:  Salom dunyo'),
  ("p","Qavs `()` ichidagi qism — bu funksiyaga beriladigan **argument**, ya'ni ekranga chiqariladigan ma'lumot. Matn (string) doimo tirnoq ichida yoziladi."),
  ("note","Matnni ikki tirnoq \" \" yoki bitta tirnoq ' ' ichida yozish mumkin. Ikkalasi ham to'g'ri."),
  ("h2","3. Bir nechta qatorni chiqarish"),
  ("p","Har bir `print()` o'z ma'lumotini yangi qatordan chiqaradi:"),
  ("code",'print("Temur, sog\'liqlaring yaxshimi?")\nprint("Javohir, maktabga bordingmi?")\nprint("Shohruh, tuzalib qoldingmi?")',
   "Har bir qator alohida chiqadi."),
  ("h2","4. f-string — matn ichiga qiymat qo'shish"),
  ("p","Ko'pincha matn ichida o'zgaruvchi qiymatini ko'rsatish kerak bo'ladi. Buning eng qulay yo'li — **f-string**. Tirnoqdan oldin `f` harfi qo'yiladi va qiymatlar `{ }` ichiga yoziladi:"),
  ("code",'ism = "Shohjahon"\nfamiliya = "Donishev"\nprint(f"Salom {ism} {familiya}, dasturga xush kelibsiz!")',
   "Natija:  Salom Shohjahon Donishev, dasturga xush kelibsiz!"),
  ("h2","5. Maxsus belgilar"),
  ("p","Matn ichida `\\n` belgisi yangi qatorga o'tkazadi, `\\t` esa tab (bo'sh joy) qo'yadi:"),
  ("code",'print("Birinchi qator\\nIkkinchi qator")',"\\n yangi qatordan boshlaydi."),
  ("h2","Xulosa"),
  ("bul",[
    "`print()` ekranga ma'lumot chiqaradi.",
    "Matn tirnoq ichida yoziladi.",
    "f-string yordamida matn ichiga qiymat qo'shamiz.",
    "`\\n` yangi qator, `\\t` tab beradi.",
  ]),
  ("h3","Mustaqil mashq"),
  ("bul",[
    "O'zingizni tanishtiruvchi 3 qatorli dastur yozing.",
    "Ism va familiyangizni o'zgaruvchiga yozib, f-string bilan chiqaring.",
  ]),
 ])

LESSONS[2] = ("Matn va sonlar bilan ishlash",
 "String, son turlari, f-string va oddiy hisob-kitoblar",
 [
  ("h2","1. Ma'lumot turlari"),
  ("p","Pythonda har bir qiymat ma'lum bir **turga** ega bo'ladi. Asosiy turlar:"),
  ("bul",[
    "**str** (string) — matn, tirnoq ichida: \"Salom\"",
    "**int** — butun son: 5, 100, -20",
    "**float** — kasrli son: 3.14, 0.5",
  ]),
  ("h2","2. Matn (string)"),
  ("p","Matnlarni `+` belgisi bilan birlashtirish (konkatenatsiya) mumkin:"),
  ("code",'ism = "Ali"\nprint("Salom, " + ism + "!")',"Natija:  Salom, Ali!"),
  ("p","Lekin matn ichiga son qo'shmoqchi bo'lsak, f-string ancha qulay:"),
  ("code",'n = "Shohjahon"\nyosh = 14\nprint(f"{n} {yosh} yoshda")',"Natija:  Shohjahon 14 yoshda"),
  ("h2","3. Sonlar bilan amallar"),
  ("p","Pythonda asosiy arifmetik amallar:"),
  ("bul",[
    "`+` qo'shish, `-` ayirish",
    "`*` ko'paytirish, `/` bo'lish",
    "`**` darajaga ko'tarish",
    "`%` qoldiqni topish (modul)",
  ]),
  ("code",'n = 5\np = 4\nprint(f"{n} ning {p}-darajasi {n**p} ga teng")',"Natija:  5 ning 4-darajasi 625 ga teng"),
  ("h2","4. \\n maxsus belgisi"),
  ("p","Bir `print()` ichida bir nechta qator chiqarish uchun `\\n` ishlatiladi:"),
  ("code",'print("Odami ersang, demagil odami\\nOnikim yo\'q xalq g\'amidin g\'ami")',
   "Ikki misra bitta print bilan chiqdi."),
  ("note","Matnda tirnoq belgisini ishlatish kerak bo'lsa, oldiga \\ qo'yiladi: \"yo\\'q\"."),
  ("h2","Xulosa"),
  ("bul",[
    "Asosiy turlar: str, int, float.",
    "Matnlar `+` bilan birlashadi, sonlar arifmetik amallarda ishtirok etadi.",
    "f-string matn va sonni qulay birlashtiradi.",
  ]),
 ])

LESSONS[3] = ("O'zgaruvchilar bilan tanishuv",
 "O'zgaruvchi yaratish, nomlash qoidalari va string metodlari",
 [
  ("h2","1. O'zgaruvchi nima?"),
  ("p","**O'zgaruvchi (variable)** — bu ma'lumot saqlanadigan \"quti\". Unga nom beramiz va `=` belgisi orqali qiymat yuklaymiz:"),
  ("code",'a = 10\nprint(a)',"Natija:  10"),
  ("p","`=` — bu \"teng\" emas, balki \"o'zlashtirish\" belgisi: o'ng tarafdagi qiymat chap tarafdagi o'zgaruvchiga yuklanadi."),
  ("h2","2. Nomlash qoidalari"),
  ("bul",[
    "Faqat harf, raqam va `_` ishlatiladi.",
    "Nom raqam bilan boshlanmaydi (1ism — xato).",
    "Bo'sh joy ishlatilmaydi (ism_familiya — to'g'ri).",
    "Katta-kichik harf farqlanadi: `ism` va `Ism` har xil.",
    "Nom ma'noli bo'lsin: `yosh`, `narx`, `ism`.",
  ]),
  ("h2","3. Qiymatni o'zgartirish"),
  ("p","O'zgaruvchiga istalgancha yangi qiymat berish mumkin:"),
  ("code",'xabar = "Salom"\nprint(xabar)\nxabar = "Xayr"\nprint(xabar)',"Avval Salom, keyin Xayr chiqadi."),
  ("h2","4. String (matn) metodlari"),
  ("p","Matn ustida foydali amallar bajaruvchi tayyor metodlar mavjud:"),
  ("code",'gap = "yashna gulla xur o\'zbekiston"\nprint(gap.title())      # Har So\'z Bosh Harf\nprint(gap.upper())      # KATTA HARF\nprint(gap.lower())      # kichik harf\nprint(gap.capitalize()) # Faqat birinchi harf katta',
   "title(), upper(), lower(), capitalize()"),
  ("h2","5. Ortiqcha bo'shliqlarni olib tashlash"),
  ("p","`strip()` matn boshi va oxiridagi bo'shliqlarni tozalaydi:"),
  ("code",'meva = "   banan   "\nprint(f"Men {meva.strip()}ni yaxshi ko\'raman!")',"Bo'shliqlar olib tashlandi."),
  ("h2","Xulosa"),
  ("bul",[
    "O'zgaruvchi `=` orqali qiymat oladi.",
    "Nom ma'noli va qoidaga mos bo'lishi kerak.",
    "String metodlari: title, upper, lower, capitalize, strip.",
  ]),
 ])

LESSONS[4] = ("Sonlar bilan ishlash",
 "int, float, type(), input() va turlarni o'zgartirish",
 [
  ("h2","1. Son turlari"),
  ("bul",[
    "**int** — butun son: 30, -20, 0",
    "**float** — kasrli son: 20.7, 3.14",
    "**bool** — mantiqiy: True yoki False",
  ]),
  ("code",'a = 30\nb = -20\nprint(a + b)',"Natija:  10"),
  ("h2","2. type() — turini bilish"),
  ("p","`type()` funksiyasi qiymatning turini ko'rsatadi:"),
  ("code",'a = 10\nb = 20.7\nc = "Python"\nd = True\nprint(type(a))  # int\nprint(type(b))  # float\nprint(type(c))  # str\nprint(type(d))  # bool',
   "Har bir qiymatning turi chiqadi."),
  ("h2","3. input() — foydalanuvchidan ma'lumot olish"),
  ("p","`input()` foydalanuvchidan klaviatura orqali ma'lumot oladi. **Muhim:** input() doimo **matn (str)** qaytaradi!"),
  ("code",'ism = input("Ismingizni kiriting: ")\nprint(f"Salom, {ism}!")',"Foydalanuvchi yozgan ism chiqadi."),
  ("h2","4. Turlarni o'zgartirish (type casting)"),
  ("p","Son bilan hisob qilish uchun matnni songa aylantirish kerak. Buning uchun `int()` yoki `float()` ishlatiladi:"),
  ("code",'yosh = int(input("Yoshingizni kiriting: "))\ntugilgan = 2025 - yosh\nprint(f"Siz {tugilgan}-yilda tug\'ilgansiz")',
   "input matnini int() songa aylantirdik."),
  ("note","Agar int() qilmasdan input() natijasini qo'shsangiz, sonlar emas, matnlar birikib ketadi. Masalan \"2\"+\"3\" = \"23\"."),
  ("h2","5. Sonni matnga aylantirish"),
  ("code",'narx = 12000\nprint("Narx: " + str(narx) + " so\'m")',"str() son matnga aylantirildi."),
  ("h2","Xulosa"),
  ("bul",[
    "Son turlari: int, float, bool.",
    "`type()` turni ko'rsatadi.",
    "`input()` har doim matn qaytaradi.",
    "`int()`, `float()`, `str()` turlarni o'zgartiradi.",
  ]),
 ])

LESSONS[5] = ("Ro'yxat (list) bilan tanishuv",
 "List yaratish, elementlarga murojaat va asosiy amallar",
 [
  ("h2","1. List nima?"),
  ("p","**List (ro'yxat)** — bu bir nechta qiymatni bitta o'zgaruvchida saqlovchi tuzilma. Qiymatlar kvadrat qavs `[ ]` ichida, vergul bilan ajratib yoziladi:"),
  ("code","mevalar = ['olma', 'anjir', 'shaftoli', \"o'rik\"]\nnarxlar = [12000, 18000, 10900, 22000]\nbosh_royxat = []",
   "Matnli, sonli va bo'sh ro'yxatlar."),
  ("h2","2. Elementlarga murojaat (indeks)"),
  ("p","Har bir element o'z **indeksi** (tartib raqami) orqali olinadi. Indeks **0 dan** boshlanadi:"),
  ("code","mevalar = ['olma', 'anjir', 'shaftoli', \"o'rik\"]\nprint(mevalar[0])   # olma\nprint(mevalar[1])   # anjir\nprint(mevalar[-1])  # o'rik (oxirgi)",
   "Manfiy indeks oxiridan sanaydi."),
  ("h2","3. Elementni o'zgartirish"),
  ("code","mevalar = ['olma', 'anjir', 'shaftoli']\nmevalar[1] = 'uzum'\nprint(mevalar)","['olma', 'uzum', 'shaftoli']"),
  ("h2","4. Element qo'shish va o'chirish"),
  ("bul",[
    "`append()` — oxiriga qo'shadi",
    "`insert(i, x)` — i-o'ringa qo'shadi",
    "`del list[i]` / `remove(x)` — o'chiradi",
    "`pop()` — oxirgini olib tashlaydi va qaytaradi",
  ]),
  ("code","mevalar = ['olma', 'anjir']\nmevalar.append('uzum')\nmevalar.insert(0, 'banan')\nprint(mevalar)","['banan', 'olma', 'anjir', 'uzum']"),
  ("h2","5. String metodlarini element ustida qo'llash"),
  ("code","mevalar = ['olma', 'anjir']\nprint(mevalar[0].title())","Olma"),
  ("h2","Xulosa"),
  ("bul",[
    "List `[ ]` ichida bir nechta qiymat saqlaydi.",
    "Indeks 0 dan boshlanadi, -1 oxirgi element.",
    "append, insert, remove, pop, del bilan o'zgartiramiz.",
  ]),
 ])

LESSONS[6] = ("Ro'yxatni tartiblash va boshqarish",
 "sort(), sorted(), reverse(), len() va tartiblash nozikliklari",
 [
  ("h2","1. Ro'yxatni tartiblash — sort()"),
  ("p","`sort()` metodi ro'yxatni alifbo yoki o'sish tartibida **butunlay o'zgartirib** tartiblaydi:"),
  ("code","cars = ['bmw', 'mercedes', 'volvo', 'tesla', 'audi']\ncars.sort()\nprint(cars)","['audi', 'bmw', 'mercedes', 'tesla', 'volvo']"),
  ("h2","2. Diqqat: katta-kichik harf"),
  ("p","Python avval BOSH harfli so'zlarni, keyin kichik harflilarni tartiblaydi. Shuning uchun harf registriga e'tibor bering:"),
  ("code","cars = ['Bmw', 'mercedes', 'Volvo', 'audi']\ncars.sort()\nprint(cars)","Bosh harflilar oldinga chiqadi."),
  ("h2","3. Teskari tartib"),
  ("code","sonlar = [3, 1, 4, 1, 5, 9, 2]\nsonlar.sort(reverse=True)\nprint(sonlar)","[9, 5, 4, 3, 2, 1, 1]"),
  ("h2","4. sorted() — vaqtinchalik tartiblash"),
  ("p","`sorted()` asl ro'yxatni o'zgartirmaydi, balki yangi tartiblangan ro'yxat qaytaradi:"),
  ("code","cars = ['volvo', 'audi', 'bmw']\nprint(sorted(cars))  # vaqtincha tartiblangan\nprint(cars)          # asl ro'yxat o'zgarmadi",
   "sort() o'zgartiradi, sorted() qaytaradi."),
  ("h2","5. reverse() va len()"),
  ("code","cars = ['audi', 'bmw', 'volvo']\ncars.reverse()       # tartibni aylantiradi\nprint(cars)\nprint(len(cars))     # nechta element borligini sanaydi",
   "reverse — teskari, len — uzunlik."),
  ("h2","Xulosa"),
  ("bul",[
    "`sort()` ro'yxatni doimiy tartiblaydi.",
    "`sorted()` yangi tartiblangan nusxa qaytaradi.",
    "`reverse=True` o'sish o'rniga kamayish tartibi.",
    "`len()` elementlar sonini beradi.",
  ]),
 ])

LESSONS[7] = ("For tsikli — ro'yxat bilan ishlash",
 "Takrorlash, for tsikli, indentatsiya va range()",
 [
  ("h2","1. Tsikl nima va nega kerak?"),
  ("p","Agar ro'yxatdagi har bir element bilan bir xil ish qilmoqchi bo'lsak, har birini alohida yozish o'rniga **for tsikli** ishlatamiz. Tsikl — bu takrorlanuvchi amal."),
  ("code","mehmonlar = ['Ali', 'Vali', 'Hasan', 'Husan']\nfor mehmon in mehmonlar:\n    print(mehmon)",
   "Har bir mehmon alohida chiqadi."),
  ("h2","2. Indentatsiya (chekinish) muhim!"),
  ("p","`for` qatoridan keyin keladigan blok **4 ta bo'shliq** bilan ichkariga suriladi. Bu Python uchun majburiy — qaysi kod tsikl ichida ekanini ko'rsatadi."),
  ("note","Indentatsiya buzilsa, Python `IndentationError` xatosini beradi. Tabni emas, 4 bo'shliqni ishlating."),
  ("h2","3. Tsikl ichida f-string"),
  ("code","mehmonlar = ['Ali', 'Vali', 'Hasan']\nfor mehmon in mehmonlar:\n    print(f\"Hurmatli {mehmon}, sizni oshga taklif qilamiz!\")\n    print(\"Hurmat bilan, Olimovlar oilasi\\n\")",
   "Har bir mehmonga taklifnoma chiqadi."),
  ("h2","4. range() — sonlar ketma-ketligi"),
  ("p","Ma'lum marta takrorlash uchun `range()` ishlatiladi:"),
  ("code","for i in range(1, 6):\n    print(i)","1 dan 5 gacha chiqadi (6 kirmaydi)."),
  ("p","Sonlar ro'yxatini yaratish va yig'indini topish:"),
  ("code","yigindi = 0\nfor son in range(1, 101):\n    yigindi = yigindi + son\nprint(yigindi)","1+2+...+100 = 5050"),
  ("h2","5. Tsikldan keyingi kod"),
  ("code","mehmonlar = ['Ali', 'Vali']\nfor mehmon in mehmonlar:\n    print(mehmon)\nprint(\"Hammasi taklif qilindi!\")  # tsikldan tashqarida",
   "Chekinmagan qator tsikldan keyin bir marta ishlaydi."),
  ("h2","Xulosa"),
  ("bul",[
    "`for ... in ...:` har bir element bilan ishlaydi.",
    "Indentatsiya (4 bo'shliq) majburiy.",
    "`range(a, b)` a dan b-1 gacha sonlar beradi.",
  ]),
 ])

LESSONS[8] = ("Taqqoslash operatorlari va if",
 "Mantiqiy taqqoslash, if/else va shartli kod",
 [
  ("h2","1. Taqqoslash operatorlari"),
  ("p","Ikki qiymatni solishtirish natijasi `True` (rost) yoki `False` (yolg'on) bo'ladi:"),
  ("bul",[
    "`==` teng, `!=` teng emas",
    "`>` katta, `<` kichik",
    "`>=` katta yoki teng, `<=` kichik yoki teng",
  ]),
  ("code","print(5 == 5)   # True\nprint(5 != 3)   # True\nprint(10 > 20)  # False","Taqqoslash natijasi True/False."),
  ("h2","2. if shart operatori"),
  ("p","`if` — agar shart `True` bo'lsa, ichidagi kodni bajaradi:"),
  ("code","ism = input('Ismingiz: ')\nif ism.lower() == 'ali':\n    print('Salom, Ali!')",
   "Faqat ism Ali bo'lsa salom beradi."),
  ("h2","3. if ... else"),
  ("p","`else` — shart bajarilmasa, boshqa amalni bajaradi:"),
  ("code","avtolar = ['audi', 'bmw', 'volvo']\nfor avto in avtolar:\n    if avto == 'bmw':\n        print(avto.upper())   # BMW\n    else:\n        print(avto.title())   # Audi, Volvo",
   "bmw uchun katta harf, qolganiga bosh harf."),
  ("h2","4. Mantiqiy operatorlar: and, or, not"),
  ("bul",[
    "`and` — ikkala shart ham rost bo'lsa",
    "`or` — kamida bittasi rost bo'lsa",
    "`not` — shartni teskari qiladi",
  ]),
  ("code","yosh = 20\nif yosh >= 18 and yosh < 65:\n    print('Mehnatga layoqatli yosh')",
   "Ikkala shart bajarilsa chiqadi."),
  ("h2","5. Ro'yxatda tekshirish: in"),
  ("code","avtolar = ['audi', 'bmw']\nif 'bmw' in avtolar:\n    print('bmw mavjud')","in — elementning borligini tekshiradi."),
  ("h2","Xulosa"),
  ("bul",[
    "Taqqoslash natijasi True/False.",
    "`if` shartli kodni bajaradi, `else` aks holda.",
    "`and`, `or`, `not` shartlarni birlashtiradi.",
    "`in` ro'yxatda borligini tekshiradi.",
  ]),
 ])

LESSONS[9] = ("Shart operatorlari — if / elif / else",
 "Ko'p tarmoqli shartlar va amaliy misollar",
 [
  ("h2","1. elif — bir nechta shart"),
  ("p","Ko'pincha ikkitadan ortiq holatni tekshirish kerak bo'ladi. `elif` (else if) yordamida bir nechta shartni ketma-ket tekshiramiz:"),
  ("code","yosh = int(input('Yoshingiz: '))\nif yosh <= 4:\n    print('Kirish bepul')\nelif yosh <= 12:\n    print('Kirish 5000 so\'m')\nelse:\n    print('Kirish 10000 so\'m')",
   "Yoshga qarab narx aniqlanadi."),
  ("h2","2. Ishlash tartibi"),
  ("p","Python shartlarni **yuqoridan pastga** tekshiradi. Birinchi `True` bo'lgan shart bajariladi va qolganlari tekshirilmaydi. Shuning uchun shartlar tartibi muhim."),
  ("h2","3. Qiymatni o'zgaruvchiga yozish"),
  ("p","Ko'pincha shart natijasini o'zgaruvchiga yozib, keyin bir marta chiqarish qulay:"),
  ("code","yosh = int(input('Yoshingiz: '))\nif yosh <= 4:\n    narx = 0\nelif yosh <= 12:\n    narx = 5000\nelse:\n    narx = 10000\nprint(f\"Kirish narxi: {narx} so'm\")",
   "Kod tozaroq va o'qishga qulay."),
  ("h2","4. Diapazonni tekshirish"),
  ("p","Pythonda diapazonni qisqa yozish mumkin: `0 <= ball <= 100`"),
  ("code","ball = int(input('Ball (0-100): '))\nif 0 <= ball <= 54:\n    print('Baho: 2')\nelif 55 <= ball <= 69:\n    print('Baho: 3')\nelif 70 <= ball <= 84:\n    print('Baho: 4')\nelse:\n    print('Baho: 5')",
   "Ballni bahoga aylantirish."),
  ("h2","5. son raqamlarni ajratish"),
  ("p","Katta sonlarni o'qishga qulay qilish uchun `_` ishlatish mumkin: `10_000` = 10000."),
  ("h2","Xulosa"),
  ("bul",[
    "`elif` ko'p shartni ketma-ket tekshiradi.",
    "Birinchi rost shart ishlaydi, qolgani o'tkazib yuboriladi.",
    "Shartlar tartibi natijaga ta'sir qiladi.",
    "Diapazon: `a <= x <= b`.",
  ]),
 ])

LESSONS[10] = ("Amaliy masalalar — shartlar bilan",
 "if/elif/else yordamida hayotiy masalalarni yechish",
 [
  ("h2","1. Masala yechish bosqichlari"),
  ("bul",[
    "Masalani o'qib, **kirish** va **chiqish** ma'lumotlarini aniqlang.",
    "Qaysi shartlar borligini yozib oling.",
    "Shartlarni `if/elif/else` ko'rinishida tuzing.",
    "Dasturni turli qiymatlar bilan sinab ko'ring.",
  ]),
  ("h2","2. Masala: Bahoni aniqlash"),
  ("code","ball = int(input('Ballingizni kiriting (0-100): '))\nif 0 <= ball <= 54:\n    print('Sizning bahoyingiz: 2')\nelif 55 <= ball <= 69:\n    print('Sizning bahoyingiz: 3')\nelif 70 <= ball <= 84:\n    print('Sizning bahoyingiz: 4')\nelif 85 <= ball <= 100:\n    print('Sizning bahoyingiz: 5')\nelse:\n    print('Notog\\'ri qiymat!')",
   "Ballga qarab baho qo'yiladi."),
  ("h2","3. Masala: Ob-havoga qarab maslahat"),
  ("code","harorat = int(input('Havo harorati: '))\nif harorat < 0:\n    print('Juda sovuq! Issiq kiyining.')\nelif 0 <= harorat <= 15:\n    print('Salqin, kurtka kiying.')\nelif 16 <= harorat <= 25:\n    print('Ob-havo yaxshi.')\nelse:\n    print('Issiq! Ko\\'proq suv iching.')",
   "Haroratga mos maslahat beradi."),
  ("h2","4. Masala: Taksi narxi"),
  ("code","masofa = int(input('Masofa (km): '))\nif masofa <= 5:\n    print('Narx: 5000 so\\'m')\nelif masofa <= 15:\n    print('Narx: 10000 so\\'m')\nelse:\n    print('Narx: 20000 so\\'m')",
   "Masofaga qarab taksi narxi."),
  ("note","Foydalanuvchi notog'ri qiymat kiritishi mumkin. Doimo `else` orqali xato holatni ham hisobga oling."),
  ("h2","Xulosa"),
  ("bul",[
    "Masalani kirish/chiqishga ajratib tahlil qiling.",
    "Shartlarni mantiqiy tartibda joylashtiring.",
    "Dasturni turli holatlar bilan sinang.",
  ]),
 ])
